---
all:
  children:
    samba_dc_servers:
      children:
        samba_dc_primary:
          hosts:
            dc1:
              ansible_host: 10.1.0.61
        samba_dc_secondary:
          hosts:
            dc2:
              ansible_host: 10.1.0.62
        samba_dc_rodc:
          children:
            samba_dc_secondary:
