---
- name: Restart samba-ad-dc
  ansible.builtin.systemd:
    name: samba-ad-dc
    state: restarted
  become: true

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
  become: true
